### 1. LOGIN
POST http://localhost:5143/api/v1/auth/login
Content-Type: application/json

{
  "username": "thanhnhat",
  "password": "luongthanhnhat23"
}

### 2. CHAT MESSAGE 
POST http://localhost:5143/api/v1/chat/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA2MGFhNmFlLTk0ZWYtNGZkOS1iZDAzLTM1NjRkYzVkYmRkMSIsInVzZXJfaWQiOiIwNjBhYTZhZS05NGVmLTRmZDktYmQwMy0zNTY0ZGM1ZGJkZDEiLCJ1c2VyTmFtZSI6IlRoYW5oTmhhdCIsImVtYWlsIjoibHVvbmd0aGFuaG5oYXQ1NjdAZ21haWwuY29tIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzc3MDQ5OTQ2LCJpc3MiOiJDaW5lbWFBUEkiLCJhdWQiOiJDaW5lbWFDbGllbnQifQ.JpjzEwBHLU1B18GVRR8IHpD3fT6YHfTKgBPfjrDp8WU
Content-Type: application/json

{
  "message": "Cho tôi thông tin về phim Chainsaw man"
}
