// <auto-generated />
using System;
using CinemaAPI.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CinemaAPI.Models.Actor", b =>
                {
                    b.Property<int>("actor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("actor_id"));

                    b.Property<string>("biography")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateOnly?>("birthday")
                        .HasColumnType("date");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("place_of_birth")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("profile_path")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("actor_id");

                    b.HasIndex("name");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("CinemaAPI.Models.BlacklistedToken", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("id");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("BlacklistedTokens");
                });

            modelBuilder.Entity("CinemaAPI.Models.Booking", b =>
                {
                    b.Property<int>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("booking_id"));

                    b.Property<int?>("coupon_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("discountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("finalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("showtime_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("booking_id");

                    b.HasIndex("coupon_id");

                    b.HasIndex("createAt");

                    b.HasIndex("showtime_id");

                    b.HasIndex("status");

                    b.HasIndex("user_id", "createAt")
                        .IsDescending(false, true);

                    b.HasIndex("user_id", "status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CinemaAPI.Models.BookingSnacks", b =>
                {
                    b.Property<int>("booking_id")
                        .HasColumnType("int");

                    b.Property<int>("snack_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("booking_id", "snack_id");

                    b.HasIndex("snack_id");

                    b.ToTable("BookingSnacks");
                });

            modelBuilder.Entity("CinemaAPI.Models.Cinema", b =>
                {
                    b.Property<int>("cinema_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cinema_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("image_overview")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<int>("location_id")
                        .HasColumnType("int");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("cinema_id");

                    b.HasIndex("location_id");

                    b.HasIndex("name");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("CinemaAPI.Models.ComboDetail", b =>
                {
                    b.Property<int>("combo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("combo_id"));

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("snack_id")
                        .HasColumnType("int");

                    b.HasKey("combo_id");

                    b.HasIndex("snack_id");

                    b.ToTable("ComboDetails");
                });

            modelBuilder.Entity("CinemaAPI.Models.Coupon", b =>
                {
                    b.Property<int>("coupon_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("coupon_id"));

                    b.Property<string>("applies_to")
                        .HasColumnType("longtext");

                    b.Property<string>("code")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("discountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("maxDiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("minOrderValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("coupon_id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("startDate", "endDate");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("CinemaAPI.Models.Genre", b =>
                {
                    b.Property<int>("genre_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("genre_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("genre_id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("CinemaAPI.Models.Inventory", b =>
                {
                    b.Property<int>("snack_id")
                        .HasColumnType("int");

                    b.Property<int>("cinema_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("snack_id", "cinema_id");

                    b.HasIndex("cinema_id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("CinemaAPI.Models.Location", b =>
                {
                    b.Property<int>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("location_id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.HasKey("location_id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CinemaAPI.Models.Movie", b =>
                {
                    b.Property<int>("movie_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("movie_id"));

                    b.Property<bool?>("adult")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("backdrop_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("overview")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("poster_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("release_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("runtime")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tmdb_id")
                        .HasColumnType("longtext");

                    b.Property<string>("trailer_url")
                        .HasColumnType("longtext");

                    b.Property<double>("vote_average")
                        .HasColumnType("double");

                    b.Property<int>("vote_count")
                        .HasColumnType("int");

                    b.HasKey("movie_id");

                    b.HasIndex("status");

                    b.HasIndex("title");

                    b.HasIndex("release_date", "end_date");

                    b.HasIndex("status", "release_date")
                        .IsDescending(false, true);

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaAPI.Models.MovieActor", b =>
                {
                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.Property<int>("actor_id")
                        .HasColumnType("int");

                    b.Property<string>("char_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.HasKey("movie_id", "actor_id");

                    b.HasIndex("actor_id");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("CinemaAPI.Models.MovieGenre", b =>
                {
                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.Property<int>("genre_id")
                        .HasColumnType("int");

                    b.HasKey("movie_id", "genre_id");

                    b.HasIndex("genre_id");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("CinemaAPI.Models.Payment", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("payment_id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("booking_id")
                        .HasColumnType("int");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("paidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("provider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("refundAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("refund_code")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("transaction_code")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("payment_id");

                    b.HasIndex("booking_id");

                    b.HasIndex("paidAt");

                    b.HasIndex("status");

                    b.HasIndex("transaction_code")
                        .IsUnique();

                    b.HasIndex("status", "paidAt");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CinemaAPI.Models.PointTransaction", b =>
                {
                    b.Property<Guid>("transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("booking_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("occurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("transaction_id");

                    b.HasIndex("booking_id")
                        .IsUnique();

                    b.HasIndex("user_id", "occurredAt")
                        .IsDescending(false, true);

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("CinemaAPI.Models.Room", b =>
                {
                    b.Property<int>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("room_id"));

                    b.Property<int>("cinema_id")
                        .HasColumnType("int");

                    b.Property<int>("column")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<string>("nameRoom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("roomLayoutType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("row")
                        .HasColumnType("int");

                    b.HasKey("room_id");

                    b.HasIndex("cinema_id");

                    b.HasIndex("roomLayoutType");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CinemaAPI.Models.Seat", b =>
                {
                    b.Property<int>("seat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("seat_id"));

                    b.Property<int>("column_index")
                        .HasColumnType("int");

                    b.Property<int>("room_id")
                        .HasColumnType("int");

                    b.Property<int>("row_index")
                        .HasColumnType("int");

                    b.Property<string>("seat_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("type_id")
                        .HasColumnType("int");

                    b.HasKey("seat_id");

                    b.HasIndex("type_id");

                    b.HasIndex("room_id", "seat_code");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("CinemaAPI.Models.SeatType", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("type_id"));

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("type_id");

                    b.ToTable("SeatTypes");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTime", b =>
                {
                    b.Property<int>("showtime_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("showtime_id"));

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("movie_id")
                        .HasColumnType("int");

                    b.Property<int>("room_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("showtime_id");

                    b.HasIndex("startTime");

                    b.HasIndex("movie_id", "startTime");

                    b.HasIndex("room_id", "startTime");

                    b.ToTable("ShowTimes");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTimePrice", b =>
                {
                    b.Property<int>("type_id")
                        .HasColumnType("int");

                    b.Property<int>("showtime_id")
                        .HasColumnType("int");

                    b.Property<decimal>("base_price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("type_id", "showtime_id");

                    b.HasIndex("showtime_id");

                    b.ToTable("ShowTimePrices");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTimeSeat", b =>
                {
                    b.Property<int>("showtime_id")
                        .HasColumnType("int");

                    b.Property<int>("seat_id")
                        .HasColumnType("int");

                    b.Property<int?>("booking_id")
                        .HasColumnType("int");

                    b.Property<string>("held_by_user")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("hold_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("hold_token")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("stseat_id")
                        .HasColumnType("int");

                    b.HasKey("showtime_id", "seat_id");

                    b.HasIndex("booking_id");

                    b.HasIndex("hold_token");

                    b.HasIndex("seat_id");

                    b.HasIndex("showtime_id", "seat_id")
                        .IsUnique();

                    b.HasIndex("showtime_id", "status");

                    b.ToTable("ShowTimeSeats");
                });

            modelBuilder.Entity("CinemaAPI.Models.Snack", b =>
                {
                    b.Property<int>("snack_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("snack_id"));

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("deleted_by")
                        .HasColumnType("char(36)");

                    b.Property<string>("imageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("snack_id");

                    b.ToTable("Snacks");
                });

            modelBuilder.Entity("CinemaAPI.Models.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("avatar_path")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("isBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("passwordResetToken")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("resetTokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("verificationToken")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("verificationTokenExpires")
                        .HasColumnType("datetime(6)");

                    b.HasKey("user_id");

                    b.HasIndex("passwordResetToken");

                    b.HasIndex("role");

                    b.HasIndex("verificationToken");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CinemaAPI.Models.UserVoucher", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("coupon_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("usedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("user_id", "coupon_id");

                    b.HasIndex("coupon_id");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("CinemaAPI.Models.Booking", b =>
                {
                    b.HasOne("CinemaAPI.Models.Coupon", "Coupon")
                        .WithMany("Bookings")
                        .HasForeignKey("coupon_id");

                    b.HasOne("CinemaAPI.Models.ShowTime", "ShowTime")
                        .WithMany("Bookings")
                        .HasForeignKey("showtime_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("ShowTime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaAPI.Models.BookingSnacks", b =>
                {
                    b.HasOne("CinemaAPI.Models.Booking", "Booking")
                        .WithMany("BookingSnacks")
                        .HasForeignKey("booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Snack", "Snack")
                        .WithMany("BookingSnacks")
                        .HasForeignKey("snack_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Snack");
                });

            modelBuilder.Entity("CinemaAPI.Models.Cinema", b =>
                {
                    b.HasOne("CinemaAPI.Models.Location", "Location")
                        .WithMany("Cinemas")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CinemaAPI.Models.ComboDetail", b =>
                {
                    b.HasOne("CinemaAPI.Models.Snack", "Snack")
                        .WithMany("ComboDetails")
                        .HasForeignKey("snack_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snack");
                });

            modelBuilder.Entity("CinemaAPI.Models.Inventory", b =>
                {
                    b.HasOne("CinemaAPI.Models.Cinema", "Cinema")
                        .WithMany("Inventories")
                        .HasForeignKey("cinema_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Snack", "Snack")
                        .WithMany("Inventory")
                        .HasForeignKey("snack_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Snack");
                });

            modelBuilder.Entity("CinemaAPI.Models.MovieActor", b =>
                {
                    b.HasOne("CinemaAPI.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("actor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaAPI.Models.MovieGenre", b =>
                {
                    b.HasOne("CinemaAPI.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("genre_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaAPI.Models.Payment", b =>
                {
                    b.HasOne("CinemaAPI.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CinemaAPI.Models.PointTransaction", b =>
                {
                    b.HasOne("CinemaAPI.Models.Booking", "Booking")
                        .WithOne("PointTransaction")
                        .HasForeignKey("CinemaAPI.Models.PointTransaction", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.User", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaAPI.Models.Room", b =>
                {
                    b.HasOne("CinemaAPI.Models.Cinema", "Cinema")
                        .WithMany("Rooms")
                        .HasForeignKey("cinema_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CinemaAPI.Models.Seat", b =>
                {
                    b.HasOne("CinemaAPI.Models.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.SeatType", "SeatType")
                        .WithMany("Seats")
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("SeatType");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTime", b =>
                {
                    b.HasOne("CinemaAPI.Models.Movie", "Movie")
                        .WithMany("ShowTimes")
                        .HasForeignKey("movie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTimePrice", b =>
                {
                    b.HasOne("CinemaAPI.Models.ShowTime", "ShowTime")
                        .WithMany()
                        .HasForeignKey("showtime_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.SeatType", "SeatType")
                        .WithMany("ShowTimePrices")
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatType");

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTimeSeat", b =>
                {
                    b.HasOne("CinemaAPI.Models.Booking", "Booking")
                        .WithMany("ShowTimeSeats")
                        .HasForeignKey("booking_id");

                    b.HasOne("CinemaAPI.Models.Seat", "Seat")
                        .WithMany("ShowTimeSeats")
                        .HasForeignKey("seat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.ShowTime", "ShowTime")
                        .WithMany("ShowTimeSeats")
                        .HasForeignKey("showtime_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("CinemaAPI.Models.UserVoucher", b =>
                {
                    b.HasOne("CinemaAPI.Models.Coupon", "Coupons")
                        .WithMany("UserVouchers")
                        .HasForeignKey("coupon_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaAPI.Models.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupons");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaAPI.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("CinemaAPI.Models.Booking", b =>
                {
                    b.Navigation("BookingSnacks");

                    b.Navigation("Payments");

                    b.Navigation("PointTransaction");

                    b.Navigation("ShowTimeSeats");
                });

            modelBuilder.Entity("CinemaAPI.Models.Cinema", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CinemaAPI.Models.Coupon", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("CinemaAPI.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CinemaAPI.Models.Location", b =>
                {
                    b.Navigation("Cinemas");
                });

            modelBuilder.Entity("CinemaAPI.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieGenres");

                    b.Navigation("ShowTimes");
                });

            modelBuilder.Entity("CinemaAPI.Models.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("CinemaAPI.Models.Seat", b =>
                {
                    b.Navigation("ShowTimeSeats");
                });

            modelBuilder.Entity("CinemaAPI.Models.SeatType", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("ShowTimePrices");
                });

            modelBuilder.Entity("CinemaAPI.Models.ShowTime", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ShowTimeSeats");
                });

            modelBuilder.Entity("CinemaAPI.Models.Snack", b =>
                {
                    b.Navigation("BookingSnacks");

                    b.Navigation("ComboDetails");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CinemaAPI.Models.User", b =>
                {
                    b.Navigation("PointTransactions");

                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
